default: &default
  adapter: postgresql
  encoding: unicode
  username: mricano
  password: mricano
  host: localhost
  pool: 5

development:
  <<: *default
  database: restaurant_reviews_dev

test:
  <<: *default
  database: restaurant_reviews_test